### ISSUE TITLE
old doc pages are still showing 

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt.github.io#2]
Pages from benchopt 1.4.1.dev11 are still present, e.g. https://benchopt.github.io/config.html

We also have some old files, that changed namespace since : https://github.com/benchopt/benchopt.github.io/blob/main/generated/benchopt.utils.datasets.simulated.make_correlated_data.html, https://github.com/benchopt/benchopt.github.io/blob/main/generated/benchopt.base.BaseObjective.html

My guess is that once something is in `generated`, it never disappears from here even if we delete the script that generated it? 
We'd need to `rm generated` before [this line](https://github.com/benchopt/benchopt/blob/main/.circleci/config.yml#L140) ? Or be even more aggressive, since `config.html` is at the root?

@tanglef @tomMoral

**Comment by tanglef** [comment]
Looked a bit into it, two things mainly (I mostly propose something as I'm not a big expert with sphinx and the current ci deployment of the website):
- there's a list of `html` files (not all, those with last update 9-10mth ago) at the folder root that are untouched by the `git clean` because they are tracked. They are both not updated and never removed. I vote for a removal + untrack them manually
- The [config file](https://github.com/benchopt/benchopt/blob/main/.circleci/config.yml#L140) runs a `git clean -xdf` and then copies all the new built files in `benchopt.github.io`. The `git clean -xdf` removes ignored files contained in `doc/**/generated`, but the `doc/_build/html/generated/` directory itself is currently not removed. (the files needed for the current version of the doc are in `user_guid/generated/`. So we should add it in the `.gitignore` of this repo?
